apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-external-issuer.fullname" . }}-clusterissuer-viewer-role
  labels:
  {{- include "cert-external-issuer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cert.dana.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert.dana.io
  resources:
  - clusterissuers/status
  verbs:
  - get