{{ if .Values.approver.issuerEnabled }}
apiVersion: cert.dana.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.issuer.namespace }}
spec:
  downloadEndpoint: {{ .Values.issuer.downloadEndpoint }}
  apiEndpoint: {{ .Values.issuer.apiEndpoint }}
  authSecretName: {{ .Values.issuerSecret.name }}
  httpConfig:
    skipVerifyTLS: {{ .Values.issuer.httpConfig.skipVerifyTLS }}
    waitTimeout: {{ .Values.issuer.httpConfig.waitTimeout }}
    retryBackoff:
      duration: {{ .Values.issuer.httpConfig.retryBackoff.duration }}
      steps: {{ .Values.issuer.httpConfig.retryBackoff.steps }}
  form: {{ .Values.issuer.form }}
  certificateRestrictions:
    {{- toYaml .Values.issuer.certificateRestrictions | nindent 4 }}
{{ end }}