apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-external-issuer.fullname" . }}-leader-election-rolebinding
  labels:
  {{- include "cert-external-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cert-external-issuer.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}