apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-external-issuer.fullname" . }}-proxy-rolebinding
  labels:
  {{- include "cert-external-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-external-issuer.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cert-external-issuer.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}